version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: sh -c "npm run build"
    ports:
      - 8000:3000
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run setup"
    ports:
      - 8001:3001
    working_dir: /app
    volumes:
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    depends_on:
      - db
  db:
    image: postgres
    environment:
       - POSTGRES_USER=user
       - POSTGRES_DB=postgresdb
       - POSTGRES_PASSWORD=password
    volumes:
       - ./db/data/postgres:/var/lib/postgresql/data  
    ports:
       - 5432:5432